### ISSUE TITLE
External resources

### ISSUE THREAD

**Issue by davidmw** [botui/botui#47]
What a great project and looks very useful for devs!  Hope to see it continue to mature and improve.

In botui.js there are some external resources:
```
    _fontAwesome = 'https://use.fontawesome.com/ea731dcb6f.js',
    _esPromisePollyfill = 'https://cdn.jsdelivr.net/es6-promise/4.1.0/es6-promise.min.js'; // mostly for IE
```
It would be great to see more configuration options supported.  I need to host everything locally, would probably use Material Design Icons (since I already have them loaded) rather than FontAwesome. and the URLs probably don't belong in the main script.

**Comment by moinism** [comment]
Thanks @davidmw!
Good idea, I'm working on its next version and will add this config option for sure.

**Comment by semmel** [comment]
>  I need to host everything locally, would probably use Material Design Icons (since I already have them loaded) rather than FontAwesome

> I'm working on its next version and will add this config option for sure. 
:+1: 

@moinism 
I need to server everything *locally* too and also would like to use svg icons *not from FontAwesome*. (Please don't upgrade to FontAwesome 5! *). It would be great if the user could configure his/her own icon template, e.g. for buttons. My would look like this:
```html
<!-- Mustache template -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
	<g><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#{{action.text.button.icon}}"></use></g>
</svg>
```
This is because I embed my [svg icons as symbols](https://css-tricks.com/svg-symbol-good-choice-icons/) in the document.

----
\* I don't like the idea that in version 5 of FontAwesome they track DOM tree changes to replace `<i>`'s with `<svg>`'s. SVGs are great but I dont like that extra JS magic messing with the DOM. Furthermore it makes inspecting elements in the developer tools a pain. It may be great for websites but not for SPA's.
